---
title: "Base R: Stock Analysis"
format: html
editor: visual
---

```{r}
rm(list=ls())
stocks <- read.csv("./IBM.csv")
stocks$Date <- as.Date(stocks$Date,format="%m/%d/%Y")
# stocks$volume <- stocks$Vol.*1000

```
```{r}
# Calculate Rolling Means
# 7 Days
stocks$SMA7 <- stats::filter(stocks$Close,
                        rep(1/7, 7),
                        sides = 2)

# 20 Days
stocks$SMA20<- stats::filter(stocks$Close, rep(1/20, 20), sides = 2)
# stocks$SMA20_filled <- as.numeric(stocks$SMA20_filled)
# stocks$SMA20_filled[is.na(stocks$SMA20_filled)] <- # stocks$Close[is.na(stocks$SMA20_filled)]

# 50 Days
stocks$SMA50 <- stats::filter(stocks$Close,
                         rep(1/50, 50),
                         sides = 2)

summary(stocks)
```

### Plot 7 Day Moving Average

```{r}
last_date <- max(stocks$Date, na.rm = TRUE)
df_last60 <- stocks[stocks$Date >= last_date - 60, ]

# 1. Plot the closing price
plot(df_last60$Close,
     type = "l",
     col = "black",
     lwd = 2,
     main = "Closing Price with 7-Day Moving Average",
     xlab = "Index",
     ylab = "Price")

# 2. Add the 20-day moving average line
lines(df_last60$SMA7,
      col = "red",
      lwd = 2)

# 3. Add a legend
legend("topleft",
       legend = c("Close", "7-Day MA"),
       col = c("black", "red"),
       lwd = 2,
       bty = "n")
grid()

```

### 20 Day Moving Average

```{r}
last_date <- max(stocks$Date, na.rm = TRUE)
df_last60 <- stocks[stocks$Date >= last_date - 100, ]

# 1. Plot the closing price
plot(df_last60$Close,
     type = "l",
     col = "black",
     lwd = 2,
     main = "Closing Price with 7-Day Moving Average",
     xlab = "Index",
     ylab = "Price")

# 2. Add the 20-day moving average line
lines(df_last60$SMA20,
      col = "red",
      lwd = 2)

# 3. Add a legend
legend("topleft",
       legend = c("Close", "20-Day MA"),
       col = c("black", "red"),
       lwd = 2,
       bty = "n")
grid()

```


### 50 Day Moving Average

```{r}
last_date <- max(stocks$Date, na.rm = TRUE)
df_last60 <- stocks[stocks$Date >= last_date - 100, ]
# 1. Plot the closing price
plot(df_last60$Close,
     type = "l",
     col = "black",
     lwd = 2,
     main = "Closing Price with 50-Day Moving Average",
     xlab = "Index",
     ylab = "Price")

# 2. Add the 20-day moving average line
lines(df_last60$SMA50,
      col = "red",
      lwd = 2)

# 3. Add a legend
legend("topleft",
       legend = c("Close", "50-Day MA"),
       col = c("black", "red"),
       lwd = 2,
       bty = "n")
grid()
```

## Daily and Cumulative Returns
### Daily
```{r}
stocks$Daily <- (stocks$Close / c(NA, head(stocks$Close, -1))) - 1
stocks$Daily[1] <- 0
stocks$Cumulative <- cumprod(1 + stocks$Daily) - 1

```
```{r}
plot(stocks$Date,stocks$Daily,type='l',main="Daily Returns")
```

### Cumulative

```{r}
plot(stocks$Date,stocks$Cumulative,type='l',main=" Cumulative Returns")
grid()
```